version: '2'
services:
  app:
    volumes:
      - .:/calc
    command: python manage.py runserver 0.0.0.0:${DOCKER_EXPOSED_PORT}
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  gulp:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/calc
    command: gulp
  storybook:
    extends:
      file: docker-services.yml
      service: base_app
    volumes:
      - .:/calc
    stop_signal: SIGKILL
    command: npm run storybook
    ports:
      - 9001:9001
  rq_worker:
    volumes:
      - .:/calc
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  rq_scheduler:
    volumes:
      - .:/calc
    environment:
      - DEFAULT_DEBUG_EMAIL_URL=smtp://mailcatcher:25/
    links:
      - mailcatcher
  mailcatcher:
    image: tophfr/mailcatcher:latest
    ports:
      - 1080:80
